### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [Meryalvhe/Meryalvhe#2]
<h2 align="center">¡Excelente trabajo @Meryalvhe en la personalización de tu página principal y perfil de GitHub!</h2>

Recuerda que tu perfil es una ventana a tu desarrollo como desarrollador y siempre estará evolucionando a medida que aprendas nuevas tecnologías y habilidades. Sigue así y nunca dejes de explorar y mejorar tu perfil.

<h3 align="center"> ¡Sigue adelante! 👏👏👏</h3>

**Comment by Meryalvhe** [comment]
<h1 align="center"> ¡Gracias @EduardoHernandezGuzman !</h1>
<p align="center"> I keep working! </p>

<h3 align="center">
  <img src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXU1cDgzeGxmcjBkamFzcG51N2dtMHB5aDYzbWZnaG9hZjNjczZxYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PRgs2sn03T1xpCSWKe/giphy.gif" width="200" />
</h3>
